import React from 'react';
import { X } from 'lucide-react';

interface LegalModalProps {
  title: string;
  onClose: () => void;
  children: React.ReactNode;
}

const LegalModal: React.FC<LegalModalProps> = ({ title, onClose, children }) => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in">
      <div className="bg-white dark:bg-slate-900 w-full max-w-2xl max-h-[80vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col border border-slate-200 dark:border-slate-700">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800">
          <h2 className="text-xl font-bold text-slate-800 dark:text-white">{title}</h2>
          <button onClick={onClose} className="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors">
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>
        <div className="p-6 overflow-y-auto prose dark:prose-invert max-w-none text-slate-600 dark:text-slate-300 text-sm leading-relaxed">
          {children}
        </div>
      </div>
    </div>
  );
};

export const PrivacyPolicy: React.FC<{ onClose: () => void }> = ({ onClose }) => (
  <LegalModal title="Privacy Policy" onClose={onClose}>
    <p><strong>Last Updated: {new Date().toLocaleDateString()}</strong></p>
    <p>Welcome to Visualize Physics Math. We respect your privacy and are committed to protecting your personal data.</p>
    
    <h3>1. Information We Collect</h3>
    <p>We do not require account registration. We may process:</p>
    <ul className="list-disc pl-5 mb-4">
      <li><strong>Input Data:</strong> The text prompts and images you upload to generate simulations.</li>
      <li><strong>Usage Data:</strong> Anonymous metrics about how the service is accessed and used.</li>
    </ul>

    <h3>2. How We Use Your Information</h3>
    <p>We use the data solely to:</p>
    <ul className="list-disc pl-5 mb-4">
      <li>Generate the requested educational simulations via the Gemini API.</li>
      <li>Improve the performance and accuracy of our tool.</li>
    </ul>

    <h3>3. Data Sharing</h3>
    <p>Your inputs are sent to Google's Gemini API for processing. We do not sell your data to third parties.</p>

    <h3>4. Cookies</h3>
    <p>We use local storage only to save your theme preferences (Light/Dark mode). No tracking cookies are used.</p>
  </LegalModal>
);

export const TermsOfService: React.FC<{ onClose: () => void }> = ({ onClose }) => (
  <LegalModal title="Terms of Service" onClose={onClose}>
    <p><strong>Last Updated: {new Date().toLocaleDateString()}</strong></p>
    
    <h3>1. Acceptance of Terms</h3>
    <p>By accessing Visualize Physics Math, you agree to be bound by these Terms of Service.</p>

    <h3>2. Use of License</h3>
    <p>This project is open-source. You are free to use, modify, and distribute the code under the MIT License provided in the repository.</p>

    <h3>3. Disclaimer</h3>
    <p>The educational simulations are generated by AI and may occasionally contain inaccuracies. They should be used as educational aids, not as absolute scientific references for critical engineering or safety calculations.</p>

    <h3>4. User Conduct</h3>
    <p>You agree not to use the service to generate harmful, illegal, or inappropriate content.</p>

    <h3>5. API Usage</h3>
    <p>This application utilizes the Google Gemini API. By using this service, you also agree to be bound by Google's Generative AI Terms of Service.</p>
  </LegalModal>
);
